# coding: utf-8

# # Clustering using the Mean Shift algorithm
# ##### Using MeanShift to find clusters in the Titanic data set and examine each cluster

import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.cluster import MeanShift, estimate_bandwidth

### Titanic data set
# 
# <b>Download link: </b>https://www.kaggle.com/c/3136/download/train.csv
# 
# <b>Summary: </b>Information about passengers who were on the Titanic including whether they survived

print("Cargando dataset del Titanic...")
titanic_data = pd.read_csv('../data/titanic.csv', quotechar='"')
print(titanic_data.head())


# #### Drop columns which are meaningless when attempting to find patterns
# CORRECCIÓN: Se cambió 'columns' por el parámetro explícito columns=[] para evitar el TypeError
titanic_data.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)
print("\nDataset después de eliminar columnas innecesarias:")
print(titanic_data.head())


# #### Convert the gender values to numbers

le = preprocessing.LabelEncoder()
titanic_data['Sex'] = le.fit_transform(titanic_data['Sex'].astype(str))
titanic_data.head()


# #### Apply one-hot encoding for the port of Embarkation
# CORRECCIÓN: Se agrega dtype=int para que devuelva 0 y 1 en lugar de True/False
titanic_data = pd.get_dummies(titanic_data, columns=['Embarked'], dtype=int)
titanic_data.head()


# #### Check how many rows in the data frame contain null values

print("\nFilas con valores nulos:")
print(titanic_data[titanic_data.isnull().any(axis=1)])


# #### Rather than clean up all the missing NaN values, we drop them all

titanic_data = titanic_data.dropna()


# #### Use Mean Shift in order to find clusters in the data
# * The bandwidth parameter specifies the "radius" of each cluster
# * Higher bandwidths will produce fewer clusters

print("\nEntrenando el modelo de agrupamiento Mean Shift...")
analyzer = MeanShift(bandwidth=30)
analyzer.fit(titanic_data)


# #### Default bandwidth for a data set is calculated using the estimate_bandwidth function

# Getting the size of the bandwidth which MeanShift will have used by default
bw_default = estimate_bandwidth(titanic_data)
print(f"Bandwidth estimado por defecto para este dataset: {bw_default:.4f}")


# #### Fetch the labels generated by MeanShift for the Titanic data 

labels = analyzer.labels_


# #### How many clusters do we have?

unique_clusters = np.unique(labels)
print(f"Grupos (Clusters) detectados por el algoritmo: {unique_clusters}")


# #### Create a new cluster_group column in the data frame for these labels 
# CORRECCIÓN: Se reemplazó el bucle ineficiente 'for' por una asignación directa de Pandas vectorizada
titanic_data['cluster_group'] = labels
print(titanic_data.head())


# #### Examine the overall data in the data set

print("\n--- Descripción estadística global del dataset ---")
print(titanic_data.describe())


# #### Examine average data for each cluster

print("\n--- Promedios por cada grupo (Cluster) ---")
titanic_cluster_data = titanic_data.groupby(['cluster_group']).mean()
print(titanic_cluster_data)


# #### Add the counts for each cluster

titanic_cluster_data['Counts'] = pd.Series(titanic_data.groupby(['cluster_group']).size())
print("\n--- Promedios incluyendo el conteo de pasajeros por grupo ---")
print(titanic_cluster_data)


# #### Examine the data in one of the clusters

print("\n--- Descripción estadística del Grupo 1 ---")
print(titanic_data[ titanic_data['cluster_group'] == 1 ].describe())


# #### View all the rows of one cluster

print("\n--- Pasajeros pertenecientes al Grupo 0 ---")
print(titanic_data[ titanic_data['cluster_group'] == 0])